### ISSUE TITLE
insert hangs

### ISSUE THREAD

**Issue by giko45** [IMSMWU/RClickhouse#60] opened 2020-05-09 17:01 UTC
Hi,

The following hangs at the insert statment

```
dbExecute(con,"CREATE TABLE tag_join(`id` UInt32) ENGINE = Log()")
dbExecute(con,"INSERT INTO tag_join VALUES (1);")
```

**Comment by inkrement** [comment] 2020-05-09 17:55
@giko45 Thanks for reporting this bug. `dbExecute` calls `dbSendQuery` behind the scenes, which seem to hang. We'll investigate it and fit it as soon as possible.

**Comment by giko45** [comment] 2020-05-09 17:57
Thanks!

**Comment by inkrement** [comment] 2020-05-10 16:35
Hi,

we investigated this issue in more detail. It is related to the Clickhouse-cpp client, which is used in the background. Insert queries seem to return "data" on the wire protocol, which is discarded per default in case of the insert-command (see [1] for details). However, when you use the sendQuery/execute interface directly, it is not discarded, but blocks (the cpp client waits for data which is never received). 

In consequence, it cannot be directly fixed by us, but it could be targeted by the Clickhouse-cpp colleagues (https://github.com/artpaul/clickhouse-cpp). This behaviour is induced by the use of the dbExecute command for inserts. A easy "hot fix" would be to use dbWriteTable/dbAppendTable instead.

 - [1] https://github.com/ClickHouse/clickhouse-cpp/blob/a22e075ae7107074cd53181d7a4e8c74c72e23c2/clickhouse/client.cpp#L245

**Comment by giko45** [comment] 2020-05-11 08:33
dbWriteTable/dbAppendTable works fine for my case, Thanks!

**Comment by artpaul** [comment] 2020-05-18 16:36
Author of clickhouse-cpp is here. 

This is not a bug. There is just no way to pass values inside textual part of an insert query when the raw TCP protocol is used. All values should be given as a block, and there is an "Insert" method in the client.

**Comment by inkrement** [comment] 2020-05-18 16:53
@artpaul thanks for clarification! I'll close this issue for now.

**Closed by inkrement** 2020-05-18 16:53 UTC
Labels: bug
