### ISSUE TITLE
RClickhouse was removed from the CRAN repository.

### ISSUE THREAD

**Issue by gaertner-mike** [IMSMWU/RClickhouse#52] opened 2019-12-20 09:51 UTC
Not sure if that issue has been raised yet, but the package is no longer part of CRAN, can this be fixed? 

> Package ‘RClickhouse’ was removed from the CRAN repository.
> Formerly available versions can be obtained from the archive.
> Archived on 2019-12-17 as check issues were not corrected in time.

**Comment by inkrement** [comment] 2019-12-20 13:40
Hi Mike,

yes we know that already and we've been working on it for a couple of weeks. The R team is trying to support future compilers as good as possible and do not want any warnings during compilation. Therefore we had to make some changes here. In the course of this we also updated the dependencies and we came across problems with Windows. Because we have only limited access to Windows installations and we lack the experience here, we can't offer a CRAN package at the moment. But we are working on it and are trying to deliver a good package as soon as possible. There is no exact time schedule for this, but we would like to have a solution before Christmas.

many greetings

ps: If you are a linux/Mac user you can install the latest version using devtools.

**Comment by waynelapierre** [comment] 2019-12-25 03:30
Any update?

**Comment by danielw2904** [comment] 2019-12-25 09:01
The problem is a compilation error on windows. Initially there was also a bug in the upstream cpp code but that seems to be fixed. We do not have a windows machine (only a vm with limited rights) and the package compiles fine on Linux which makes debugging hard. So if you have windows could you try to compile it and post any errors here?

**Comment by vpanfilov** [comment] 2019-12-25 10:14
I got the following error during compilation from master:
```
remotes::install_github("IMSMWU/RClickhouse")

#> Error in .shlib_internal(args) :
#>   C++14 standard requested but CXX14 is not defined
```

I have Rtools version 3.5.0.4

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Russian_Russia.1251         
#>  ctype    Russian_Russia.1251         
#>  tz       Europe/Moscow               
#>  date     2019-12-25                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
#>  callr         3.4.0   2019-12-09 [1] CRAN (R 3.6.1)
#>  cli           2.0.0   2019-12-09 [1] CRAN (R 3.6.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  curl          4.3     2019-12-02 [1] CRAN (R 3.6.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
#>  digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.1)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fansi         0.4.0   2018-10-05 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
#>  knitr         1.26    2019-11-12 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
#>  rlang         0.4.2   2019-11-23 [1] CRAN (R 3.6.1)
#>  rmarkdown     2.0     2019-12-12 [1] CRAN (R 3.6.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.1)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.11    2019-11-12 [1] CRAN (R 3.6.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] C:/Users/vpanfilov/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.1/library
```

</details>

**Comment by danielw2904** [comment] 2020-01-09 17:49
We have backported to C++11. I get the following error from r-hub.

```
#> C:/Rtools34/mingw_32/bin/gcc -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG -D_WIN32_WINNT=0x0600 -I. -I../inst/include -I./vendor/clickhouse-cpp -I./vendor/clickhouse-cpp/contrib -I./vendor/clickhouse-cpp/contrib/bigerint -I'C:/Users/USERJWYrfESMoB/R/Rcpp/include' -I"c:\R\local330/include" -O2 -Wall -std=gnu99 -mtune=generic -c RClickhouse_init.c -o RClickhouse_init.o

 457#> C:/Rtools34/mingw_32/bin/g++ -std=gnu++11 -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG -D_WIN32_WINNT=0x0600 -I. -I../inst/include -I./vendor/clickhouse-cpp -I./vendor/clickhouse-cpp/contrib -I./vendor/clickhouse-cpp/contrib/bigerint -I'C:/Users/USERJWYrfESMoB/R/Rcpp/include' -I"c:\R\local330/include" -O2 -Wall -mtune=generic -c RcppExports.cpp -o RcppExports.o

 458#> In file included from ./vendor/clickhouse-cpp/clickhouse/columns/ip4.h:4:0,

 459#> from ./vendor/clickhouse-cpp/clickhouse/client.h:10,

 460#> from ../inst/include/RClickhouse.h:4,

 461#> from RcppExports.cpp:4:

 462#> ./vendor/clickhouse-cpp/clickhouse/columns/../base/socket.h:11:0: warning: ignoring #pragma comment [-Wunknown-pragmas]

 463#> # pragma comment(lib, "Ws2_32.lib")

 464#> ^

 465#> In file included from C:/PROGRA~1/R/R-devel/include/R.h:91:0,

 466#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/Rcpp/r/headers.h:71,

 467#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/RcppCommon.h:29,

 468#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/Rcpp.h:27,

 469#> from ./result.h:7,

 470#> from ../inst/include/RClickhouse.h:5,

 471#> from RcppExports.cpp:4:

 472#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:55:0: warning: "ERROR" redefined

 473#> #define ERROR ),error(R_problem_buf);}

 474#> ^

 475#> In file included from C:/Rtools34/mingw_32/i686-w64-mingw32/include/windows.h:71:0,

 476#> from ./vendor/clickhouse-cpp/clickhouse/columns/ip4.h:4,

 477#> from ./vendor/clickhouse-cpp/clickhouse/client.h:10,

 478#> from ../inst/include/RClickhouse.h:4,

 479#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/winsock2.h:23,

 480#> from RcppExports.cpp:4:

 481#> C:/Rtools34/mingw_32/i686-w64-mingw32/include/wingdi.h:75:0: note: this is the location of the previous definition

 482#> from ./vendor/clickhouse-cpp/clickhouse/columns/../base/socket.h:13,

 483#> #define ERROR 0

 484#> ^

 485#> C:/Rtools34/mingw_32/bin/g++ -std=gnu++11 -I"C:/PROGRA~1/R/R-devel/include" -DNDEBUG -D_WIN32_WINNT=0x0600 -I. -I../inst/include -I./vendor/clickhouse-cpp -I./vendor/clickhouse-cpp/contrib -I./vendor/clickhouse-cpp/contrib/bigerint -I'C:/Users/USERJWYrfESMoB/R/Rcpp/include' -I"c:\R\local330/include" -O2 -Wall -mtune=generic -c connection.cpp -o connection.o

 486#> In file included from ./vendor/clickhouse-cpp/clickhouse/columns/ip4.h:4:0,

 487#> from ./vendor/clickhouse-cpp/clickhouse/client.h:10,

 488#> ./vendor/clickhouse-cpp/clickhouse/columns/../base/socket.h:11:0: warning: ignoring #pragma comment [-Wunknown-pragmas]

 489#> # pragma comment(lib, "Ws2_32.lib")

 490#> ^

 491#> from connection.cpp:6:

 492#> In file included from C:/Rtools34/mingw_32/i686-w64-mingw32/include/combaseapi.h:155:0,

 493#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/ole2.h:17,

 494#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/objbase.h:14,

 495#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/winsock2.h:23,

 496#> from ./vendor/clickhouse-cpp/clickhouse/columns/../base/socket.h:13,

 497#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/windows.h:97,

 498#> from ./vendor/clickhouse-cpp/clickhouse/columns/ip4.h:4,

 499#> from ./vendor/clickhouse-cpp/clickhouse/client.h:10,

 500#> from connection.cpp:6:

 501#> C:/Rtools34/mingw_32/i686-w64-mingw32/include/objidlbase.h:864:18: error: macro "Realloc" requires 3 arguments, but only 2 given

 502#> SIZE_T cb) = 0;

 503#> ^

 504#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/winscard.h:10,

 505#> from C:/Rtools34/mingw_32/i686-w64-mingw32/include/wtypes.h:12,

 506#> C:/Rtools34/mingw_32/i686-w64-mingw32/include/objidlbase.h:864:22: error: 'Realloc' declared as a 'virtual' field

 507#> SIZE_T cb) = 0;

 508#> ^

 509#> In file included from C:/PROGRA~1/R/R-devel/include/R.h:91:0,

 510#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/RcppCommon.h:29,

 511#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/Rcpp/r/headers.h:71,

 512#> from C:/Users/USERJWYrfESMoB/R/Rcpp/include/Rcpp.h:27,

 513#> from connection.cpp:5:

 514#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:37: error: expected identifier before '(' token

 515#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 516#> ^

 517#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:47: error: 'parameter' declared as function returning a function

 518#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 519#> ^

 520#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:50: error: expected ')' before ',' token

 521#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 522#> ^

 523#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 524#> ^

 525#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:37: error: expected identifier before '(' token

 526#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:47: error: 'parameter' declared as function returning a function

 527#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 528#> C:/PROGRA~1/R/R-devel/include/R_ext/RS.h:74:50: error: expected ')' before ',' token

 529#> ^

 530#> #define Free(p) (R_chk_free( (void *)(p) ), (p) = NULL)

 531#> ^

 532#> connection.cpp:310:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

 533#> connection.cpp: In instantiation of 'std::shared_ptr<_Tp1> vecToEnum(SEXP, clickhouse::TypeRef, std::shared_ptr >) [with CT = clickhouse::ColumnEnum; VT = signed char; SEXP = SEXPREC*; clickhouse::TypeRef = std::shared_ptr]':

 534#> ^

 535#> for (size_t i = 0; i < levels.size(); i++) {

 536#> connection.cpp:398:58: required from here

 537#> connection.cpp: In instantiation of 'std::shared_ptr<_Tp1> vecToEnum(SEXP, clickhouse::TypeRef, std::shared_ptr >) [with CT = clickhouse::ColumnEnum; VT = short int; SEXP = SEXPREC*; clickhouse::TypeRef = std::shared_ptr]':

 538#> connection.cpp:400:60: required from here

 539#> connection.cpp:310:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

 540#> make: *** [C:/PROGRA~1/R/R-devel/etc/i386/Makeconf:215: connection.o] Error 1

 541#> ERROR: compilation failed for package 'RClickhouse'

 542#> * removing 'C:/Users/USERJWYrfESMoB/R/RClickhouse'****
```

**Comment by inkrement** [comment] 2020-01-29 04:11
Finally, we were able to fix also the windows bugs. A new version was submitted to CRAN just some seconds ago. Keep fingers crossed, but should be online again soon. 

We planed to refactor the code base and we will add automated test cases to provide a better software and avoid similar issue in future.

**Comment by inkrement** [comment] 2020-01-29 20:22
Was accepted and will be on CRAN soon. Therefore, I am closing this issue now.

**Closed by inkrement** 2020-01-29 20:22 UTC
